.deploy:npm:template: &deploy_npm_definition
  stage: deploy
  image: node:lts-alpine
  before_script:
    - npm ci
    - |
      cat << EOF > .npmrc
      @icons8:registry=$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/npm/
      ${CI_API_V4_URL#https?}/projects/$CI_PROJECT_ID/packages/npm/:_authToken=\${CI_JOB_TOKEN}
      EOF
  script:
    - npm publish

deploy:npm:i8-image-processor:
  <<: *deploy_npm_definition
  rules:
    # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
    - if: $CI_COMMIT_TAG =~ /^@icons8\/i8-image-processor@(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/